module.exports = {
  MODULES: {
    SERVICE: 'SERVICE_POC',
  },
  EVENT_TYPES: {
    SERVICE_MESSAGE_RECEIVED: 'SERVICE_MESSAGE_RECEIVED',
    SERVICE_MESSAGE_FAILED: 'SERVICE_MESSAGE_FAILED',

    AUDIT_START: 'AUDIT_START',
    AUDIT_INFO: 'AUDIT_INFO',
    AUDIT_LOG: 'AUDIT_LOG',
    AUDIT_ERROR: 'AUDIT_ERROR',
    AUDIT_DONE: 'AUDIT_DONE',

    SQL_SAVE: 'SQL_SAVE',
    SQL_FAIL: 'SQL_FAIL',

    MONGO_SAVE: 'MONGO_SAVE',
    MONGO_FAIL: 'MONGO_FAIL',

    QUEUE_SUBSCRIPTION: 'QUEUE_SUBSCRIPTION',
  },
}
